from docx import Document
from docx.shared import Inches, Pt
from pptx import Presentation
from pptx.util import Inches, Pt
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
import io
import json


class DocumentGenerator:
    """Generate documents in various formats from report content"""
    
    @staticmethod
    def generate_pdf(content: dict) -> bytes:
        """Generate PDF document using ReportLab"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#0284c7'),
            spaceAfter=30
        )
        
        report_type = content.get('report_type', 'Document')
        story.append(Paragraph(report_type, title_style))
        story.append(Spacer(1, 12))
        
        # Content
        raw_content = content.get('raw', '')
        if raw_content:
            # Parse the content and add paragraphs
            lines = raw_content.split('\n')
            for line in lines:
                if line.strip():
                    if line.startswith('#'):
                        # Heading
                        level = min(line.count('#'), 6)
                        heading_style = styles[f'Heading{level}']
                        story.append(Paragraph(line.lstrip('#').strip(), heading_style))
                    elif line.startswith('-') or line.startswith('*'):
                        # Bullet point
                        story.append(Paragraph(f"• {line.lstrip('-*').strip()}", styles['Normal']))
                    else:
                        # Regular paragraph
                        story.append(Paragraph(line.strip(), styles['Normal']))
                    story.append(Spacer(1, 6))
        
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
    
    @staticmethod
    def generate_docx(content: dict) -> bytes:
        """Generate DOCX document using python-docx"""
        doc = Document()
        
        # Title
        report_type = content.get('report_type', 'Document')
        title = doc.add_heading(report_type, level=0)
        title.style.font.size = Pt(18)
        title.style.font.color.rgb = None  # Will use default
        
        # Content
        raw_content = content.get('raw', '')
        if raw_content:
            lines = raw_content.split('\n')
            for line in lines:
                if line.strip():
                    if line.startswith('###'):
                        doc.add_heading(line.lstrip('#').strip(), level=3)
                    elif line.startswith('##'):
                        doc.add_heading(line.lstrip('#').strip(), level=2)
                    elif line.startswith('#'):
                        doc.add_heading(line.lstrip('#').strip(), level=1)
                    elif line.startswith('-') or line.startswith('*'):
                        doc.add_paragraph(line.lstrip('-*').strip(), style='List Bullet')
                    else:
                        doc.add_paragraph(line.strip())
        
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()
    
    @staticmethod
    def generate_pptx(content: dict) -> bytes:
        """Generate PPTX presentation using python-pptx"""
        prs = Presentation()
        
        # Title slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title = title_slide.shapes.title
        subtitle = title_slide.placeholders[1]
        
        report_type = content.get('report_type', 'Document')
        title.text = report_type
        subtitle.text = "Generated by DocuMind AI"
        
        # Content slides
        raw_content = content.get('raw', '')
        if raw_content:
            sections = raw_content.split('\n\n')
            for section in sections[:10]:  # Limit to 10 content slides
                if section.strip():
                    slide = prs.slides.add_slide(prs.slide_layouts[1])
                    title = slide.shapes.title
                    body = slide.placeholders[1]
                    
                    lines = section.strip().split('\n')
                    if lines:
                        title.text = lines[0].lstrip('#').strip()
                        if len(lines) > 1:
                            text_frame = body.text_frame
                            text_frame.clear()
                            for line in lines[1:]:
                                if line.strip():
                                    p = text_frame.add_paragraph()
                                    p.text = line.lstrip('-*').strip()
        
        buffer = io.BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()
    
    @staticmethod
    def generate_xlsx(content: dict) -> bytes:
        """Generate Excel spreadsheet using openpyxl"""
        wb = Workbook()
        ws = wb.active
        ws.title = content.get('report_type', 'Document')
        
        # Header
        ws['A1'] = content.get('report_type', 'Document')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')
        ws.merge_cells('A1:D1')
        
        # Content
        raw_content = content.get('raw', '')
        if raw_content:
            row = 3
            lines = raw_content.split('\n')
            for line in lines:
                if line.strip():
                    if line.startswith('#'):
                        # Heading
                        ws[f'A{row}'] = line.lstrip('#').strip()
                        ws[f'A{row}'].font = Font(bold=True)
                        row += 1
                    elif line.startswith('-') or line.startswith('*'):
                        # Bullet point
                        ws[f'A{row}'] = line.lstrip('-*').strip()
                        ws[f'A{row}'].alignment = Alignment(indent=1)
                        row += 1
                    else:
                        # Regular text
                        ws[f'A{row}'] = line.strip()
                        row += 1
        
        # Adjust column widths
        ws.column_dimensions['A'].width = 50
        
        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()
    
    @classmethod
    def generate(cls, content: dict, format: str) -> bytes:
        """Generate document in specified format"""
        format = format.lower()
        generators = {
            'pdf': cls.generate_pdf,
            'docx': cls.generate_docx,
            'pptx': cls.generate_pptx,
            'xlsx': cls.generate_xlsx
        }
        
        if format not in generators:
            raise ValueError(f"Unsupported format: {format}")
        
        return generators[format](content)
